initial hack-y working instance of spark on Grace

diff --git a/spark b/spark
--- a/spark
+++ b/spark
@@ -35,14 +35,14 @@ set -e
 ################################################################################
 # The directory used to keep information about active (pending or running)
 # and inactive (finshed, failed) clusters. Something like /data/$USER/.spark
-soc_sparkdir=./x
+soc_sparkdir=/vast/palmer/scratch/support/tl397/spark
 
 # The headnode of the cluster. Used to construct the command for setting
 # up an ssh tunnel to the spark master's web ui
-soc_headnode=x.x.x
+soc_headnode=grace1.hpc.yale.edu
 
 # Spark version to use. Assumes that a 'module load' command is available
-soc_sparkver=ver
+soc_sparkver=3.2.2-foss-2020b-Scala-2.13
 
 ################################################################################
 #                                   Globals                                    #
@@ -441,14 +441,11 @@ exit
 
 #__SBATCH__
 #! /bin/bash
-#SBATCH --constraint=cpu56,g256
 #SBATCH --nodes=<SOC_NNODES>
 #SBATCH --ntasks-per-node=1
-#SBATCH --cpus-per-task=56
-#SBATCH --mem-per-cpu=4400
+#SBATCH --exclusive
 #SBATCH --time=<SOC_TIME>
-#SBATCH --partition=multinode
-#SBATCH --gres=lscratch:380
+#SBATCH --partition=day
 #SBATCH --out=<SOC_SPARKLOGDIR>/slurm.log
 #SBATCH --signal=B:USR1@180
 
@@ -483,9 +480,9 @@ function shutdown_cluster {
 cp -r ${SCRATCH}/logs/* <SOC_SPARKLOGDIR>
 EOF
         chmod +x /tmp/soc_copy_logs.sh
-        sbcast /tmp/soc_copy_logs.sh /lscratch/${SLURM_JOB_ID}/copy_logs.sh
+        sbcast /tmp/soc_copy_logs.sh /tmp/${SLURM_JOB_ID}/copy_logs.sh
 
-    srun /lscratch/${SLURM_JOB_ID}/copy_logs.sh
+    srun /tmp/${SLURM_JOB_ID}/copy_logs.sh
     rm /tmp/soc_copy_logs.sh
     fi
 
@@ -494,16 +491,16 @@ EOF
 }
 
 prop "start" "$(date +'%F %T')"
-module load spark/<SOC_SPARKVER> || fail "Could not load spark module"
+module load Spark/<SOC_SPARKVER> || fail "Could not load spark module"
 
 ###
 ### configuration files and job setup
 ###
 
 # Set up node local scratch directories on all the nodes
-export SCRATCH="/lscratch/${SLURM_JOB_ID}"
+export SCRATCH="/tmp/${SLURM_JOB_ID}"
 export SPARK_CONF_DIR="${SCRATCH}/conf"
-srun -l mkdir "${SPARK_CONF_DIR}" \
+srun -l mkdir -p "${SPARK_CONF_DIR}" \
     && srun -l mkdir "${SCRATCH}/logs" \
     && srun -l mkdir "${SCRATCH}/work" \
     && srun -l mkdir "${SCRATCH}/local" \
@@ -536,8 +533,8 @@ prop "tunnel" "ssh -L ${SPARK_MASTER_WEBUI_PORT}:${SPARK_MASTER_HOST}:${SPARK_MA
 # create config file in tmp dir
 # NOTE: SPARK_WORKER_INSTANCES IS DEPRECATED
 cat > "/tmp/spark-env.sh" <<EOF 
-SPARK_WORKER_CORES=52
-SPARK_WORKER_MEMORY=235g
+SPARK_WORKER_CORES=20
+SPARK_WORKER_MEMORY=98g
 SPARK_WORKER_DIR=${SCRATCH}/work
 SPARK_LOCAL_DIRS=${SCRATCH}/local
 SPARK_DAEMON_MEMORY=2g
